### ISSUE TITLE
Внести изменения в проект ALT Mobile Wiki в соответствии с нововведениями версии 2.4 пакета `vitepress-plugin-enhanced-readabilities`

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTMobileWiki#25]
После обновления пакета до версии 2.4 в проекте необходимо внести следующие изменения:

- Изменить локаль в связи с добавлением локали ru-RU в плагине vitepress-plugin-git-changelog.
- Удалить массив конфигураций.

**Comment by Ampernic** [comment]
> * Удалить массив конфигураций.

_*Удалить массив локализаций_
Для vitepress-plugin-git-changelog там есть другая конфигурация, по мимо локализации, которую хотелось бы легко находить в отдельном файле

> * Изменить локаль в связи с добавлением локали ru-RU в плагине `@nolebase/vitepress-plugin-git-changelog`

Зачем менять локаль, когда ее плагин определяет сам исходя из страницы.
Достаточно просто удалить нашу локаль.

Так же есть нюансы по миграции `@nolebase/vitepress-plugin-git-changelog`
`mapAuthors` перенесен в конфиг. См. конфиг AGW и [заметки на сайте авторов](https://nolebase-integrations.ayaka.io/pages/en/releases/migrations/v2-to-v3).

**Comment by Ampernic** [comment]
Добавил ревью к 740a055

**Comment by OlegShchavelev** [comment]
> > * Удалить массив конфигураций.
> 
> _*Удалить массив локализаций_ Для vitepress-plugin-git-changelog там есть другая конфигурация, по мимо локализации, которую хотелось бы легко находить в отдельном файле
> 
> > * Изменить локаль в связи с добавлением локали ru-RU в плагине `@nolebase/vitepress-plugin-git-changelog`
> 
> Зачем менять локаль, когда ее плагин определяет сам исходя из страницы. Достаточно просто удалить нашу локаль.
> 
> Так же есть нюансы по миграции `@nolebase/vitepress-plugin-git-changelog` `mapAuthors` перенесен в конфиг. См. конфиг AGW и [заметки на сайте авторов](https://nolebase-integrations.ayaka.io/pages/en/releases/migrations/v2-to-v3).

@Ampernic, отлично! Только тебе не, кажется, что данный комментарий относится к #15, а здесь я прошу проверить правильно ли все сделал для пакета `vitepress-plugin-enhanced-readabilities`

**Comment by Ampernic** [comment]
> vitepress-plugin-enhanced-readabilities

Для него все абсолютно верно
